### ISSUE TITLE
neonblueflame tracks progress on GitHub Flow

### ISSUE THREAD

**Issue by neonblueflame** [githubteacher/developers-august-emea#15]
## Tasks
- [x] create a **branch** (git)
- [x] add some **commits** (git)
- [x] open a _pull request_ (GitHub)
- [ ] additional **commits** (git)
- [ ] _merge_ (git)
